#!/bin/sh

echo "****************************************"
echo "*Please .. Restart Enigma2 *"
echo "****************************************"
echo "* Enjoy our plugin *"
echo "****************************************"
echo "* All Rights Reserved *"
echo "* © 2024 - Lululla *"
echo "****************************************"
