#!/bin/sh

echo "****************************************"
echo "*Please .. Restart Enigma2 *"
echo "****************************************"
echo "* Enjoy our plugin *"
echo "****************************************"
echo "* All Rights Reserved *"
echo "* © 2024 - Lululla *"
echo "****************************************"
echo "Checking for an older version of vavoo in the system..."
if [ -d /usr/lib/enigma2/python/Plugins/Extensions/vavoo ]
then
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/vavoo > /dev/null 2>&1
echo "An older version of vavoo was found and removed"
echo "Proceeding to installation..."
else
echo "An older version of vavoo was not found in the system"
fi
exit 0
