name: PEP8 Aggressive Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pep8-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 autopep8

      - name: Run flake8 PEP8 aggressive checks
        run: |
          flake8 --select=E225,E226,E227,E228,E231,E261,E262,E263,E265,E266,E301,E302,E303,E306 .

      - name: Run autopep8 aggressive fix
        run: |
          autopep8 --in-place --aggressive --aggressive --recursive .

      - name: Check again after autopep8 fix
        run: |
          flake8 --select=E225,E226,E227,E228,E231,E261,E262,E263,E265,E266,E301,E302,E303,E306 .
